language: java
jdk: openjdk11
os: linux
dist: xenial

services:
  - docker

cache:
  timeout: 180
  directories:
  - "$HOME/.m2/repository"

install:
   - mvn install -U -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  # master or PRs into master, use the release profile
  - mvn test -B


## export GPG details
before_deploy:
  - 'if [[ "$TRAVIS_BRANCH" =~ master* ]]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import; fi'
  - 'if [[ "$TRAVIS_BRANCH" =~ master* ]]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust; fi'
  - 'echo "$DOCKER_API_KEY" | docker login -u "$DOCKER_USERNAME" --password-stdin'

# NOTE: tests were already run as part of the script phase
deploy:
  - provider: script
    script: "docker build -f Dockerfile.phema -t phema/phema-cqf-ruler:$TRAVIS_TAG . && docker push phema/phema-cqf-ruler:$TRAVIS_TAG"
    cleanup: false
    skip_cleanup: true # This is the current correct option, but is soon to be deprecated by the above.
    on:
      tags: true
# Remove the binaries generated by this build so that the cache isn't invalidated.
# Probably a better way to do this.
before_cache:
      - rm -rf $HOME/.m2/repository/org/opencds/cqf/parent
      - rm -rf $HOME/.m2/repository/org/opencds/cqf/common
      - rm -rf $HOME/.m2/repository/org/opencds/cqf/dstu3
      - rm -rf $HOME/.m2/repository/org/opencds/cqf/r4
      - rm -rf $HOME/.m2/repository/org/opencds/cqf/cqf-ruler-dstu3
      - rm -rf $HOME/.m2/repository/org/opencds/cqf/cqf-ruler-r4
