FROM maven:3.6.3-jdk-11 AS builder

COPY . /opt/phema
WORKDIR /opt/phema

RUN mvn package

FROM tomcat:9.0.36-jdk11-openjdk

COPY --from=builder /opt/phema/cqf-ruler-r4/target/cqf-ruler-r4.war /usr/local/tomcat/webapps/

